name: bank-churn-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn==1.6.1
      - pandas==2.2.3
      - numpy==2.2.1
      - matplotlib==3.10.0
      - seaborn==0.13.2
